name: Build OpenWrt for CMCC XR30

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main          # main 分支推送触发
    tags:
      - 'v*'          # 标签推送触发 (例如 v1.0)

env:
  BUILD_DIR: xr30
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360  # 6小时超时

    steps:
    - name: Checkout custom XR30 source
      uses: actions/checkout@v4
      with:
        path: ${{ env.BUILD_DIR }}

    - name: Cache OpenWrt build environment
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.BUILD_DIR }}/dl
          ${{ env.BUILD_DIR }}/build_dir
        key: ${{ runner.os }}-openwrt-${{ hashFiles('${{ env.BUILD_DIR }}/.config', '${{ env.BUILD_DIR }}/feeds.conf.default') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex g++ gcc-multilib \
        gawk gettext git libncurses5-dev libssl-dev python3 python3-distutils \
        rsync unzip zlib1g-dev file wget

    - name: Setup feeds
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply custom configuration
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        # 自定义 XR30 配置
        cat > $CONFIG_FILE << EOF
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt7621=y
        CONFIG_TARGET_ramips_mt7621_DEVICE_cmcc_xr30=y
        CONFIG_TARGET_ROOTFS_UBIFS=y
        CONFIG_TARGET_UBIFS_FREE_SPACE_FIXUP=y
        CONFIG_TARGET_UBIFS_JOURNAL_SIZE="512"
        CONFIG_TARGET_UBI_EB_SIZE=128
        CONFIG_TARGET_UBI_MINIO_SIZE=2048
        CONFIG_KERNEL_SLAB=y
        CONFIG_TARGET_KERNEL_PARTSIZE=32
        CONFIG_TARGET_ROOTFS_PARTSIZE=200
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_openssh-sftp-server=y
        CONFIG_PACKAGE_iperf3=y
        CONFIG_PACKAGE_tcpdump=y
        EOF
        make defconfig

    - name: Download packages
      working-directory: ${{ env.BUILD_DIR }}
      run: make download -j$(nproc)

    - name: Build OpenWrt
      working-directory: ${{ env.BUILD_DIR }}
      run: make -j$(($(nproc) - 1)) V=sc   # 减少详细输出

    - name: Collect firmware artifacts
      run: |
        # 创建 artifacts 目录
        mkdir -p artifacts
        
        # 复制所有固件文件
        cp ${{ env.BUILD_DIR }}/bin/targets/ramips/mt7621/* artifacts/
        
        # 添加时间戳文件
        date > artifacts/build_timestamp.txt
        
        # 列出所有文件
        ls -lh artifacts/

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: artifacts
        retention-days: 7  # 保留7天

    - name: Create release (on tag)
      if: success() && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
        draft: false
        prerelease: false
        tag_name: ${{ github.ref_name }}
        name: "OpenWrt for CMCC XR30 (${{ github.ref_name }})"
        body: |
          ### OpenWrt固件 for CMCC XR30
          - **设备型号**: CMCC XR30
          - **闪存**: 256MB
          - **内存**: 1GB
          - **编译时间**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          - **源码仓库**: https://github.com/123456sjj/xr30
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
