name: Build OpenWrt for CMCC XR30

on:
  workflow_dispatch:  # 手动触发
  push:
    tags:
      - 'v*'          # 标签推送触发 (例如 v1.0)

env:
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360  # 6小时超时

    steps:
    - name: Checkout LEDE source
      uses: actions/checkout@v4
      with:
        repository: 123456sjj/xr30
        ref: master
        path: lede

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
        gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip zlib1g-dev \
        file wget

    - name: Setup feeds
      working-directory: ./lede
      run: |
        echo "src-git packages https://github.com/coolsnowwolf/packages" > $FEEDS_CONF
        echo "src-git luci https://github.com/coolsnowwolf/luci" >> $FEEDS_CONF
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply XR30 config
      working-directory: ./lede
      run: |
        # 基础配置 (根据您的设备调整)
        cat > $CONFIG_FILE << EOF
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt7621=y
        CONFIG_TARGET_ramips_mt7621_DEVICE_cmcc_xr30=y
        CONFIG_TARGET_ROOTFS_SQUASHFS=y
        CONFIG_TARGET_UBIFS_FREE_SPACE_FIXUP=y
        CONFIG_TARGET_UBIFS_JOURNAL_SIZE="512"
        # 内存优化 (1GB RAM)
        CONFIG_KERNEL_SLAB=y
        # 存储优化 (256MB Flash)
        CONFIG_TARGET_KERNEL_PARTSIZE=32
        CONFIG_TARGET_ROOTFS_PARTSIZE=200
        EOF

        # 添加常用包 (按需修改)
        echo "CONFIG_PACKAGE_luci=y" >> $CONFIG_FILE
        echo "CONFIG_PACKAGE_openssh-sftp-server=y" >> $CONFIG_FILE

        make defconfig

    - name: Download packages
      working-directory: ./lede
      run: make download -j$(nproc)

    - name: Build OpenWrt
      working-directory: ./lede
      run: make -j$(nproc) V=s

    - name: Pack artifacts
      run: |
        mkdir artifacts
        cp lede/bin/targets/ramips/mt7621/*.bin artifacts/
        cp lede/bin/targets/ramips/mt7621/*.gz artifacts/
        tar -czvf openwrt_build_$(date +%Y%m%d).tar.gz artifacts/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: openwrt_build_*.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
